allowBuilds:
  '@markuxt/markuxt': false
  '@parcel/watcher': false
  esbuild: false
  sharp: true
  vue-demi: false
ignoredBuiltDependencies:
  - '@markuxt/markuxt'
minimumReleaseAgeExclude:
  - '@markuxt/markuxt'
